package com.vaadin.starter.beveragebuddy.backend;

import java.io.Serializable;
import java.time.LocalDate;

/**
 * Represents a beverage review.
 */
public class Review implements Serializable {

  private Long id = null;
  private String name;
  private LocalDate date;
  private String type;

  /**
   * Default constructor.
   */
  public Review() {
    reset();
  }

  /**
   * Constructs a new instance with the given data.
   *
   * @param name     Name of beverage reviewed
   * @param date     Last review date
   */
  public Review(String name, LocalDate date, String type) {
    this.name = name;
    this.date = date;
    this.type = type;
  }

  /**
   * Copy constructor.
   *
   * @param other The instance to copy
   */
  public Review(Review other) {
    this(other.getName(), other.getDate(), other.getType());
    this.id = other.getId();
  }

  /**
   * Resets all fields to their default values.
   */
  public void reset() {
    this.id = null;
    this.name = "";
    this.date = LocalDate.now();
    this.type = "";
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  /**
   * Gets the value of name
   *
   * @return the value of name
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of name
   *
   * @param name new value of name
   */
  public void setName(String name) {
    this.name = name;
  }


  /**
   * Gets the value of date
   *
   * @return the value of date
   */
  public LocalDate getDate() {
    return date;
  }

  /**
   * Sets the value of date
   *
   * @param date new value of date
   */
  public void setDate(LocalDate date) {
    this.date = date;
  }

  @Override
  public String toString() {
    // Must use getters instead of direct member access,
    // to make it work with proxy objects generated by the view model
    return "Review{" + "id=" + getId() + ", name="
      + getName() + ", date="
      + getDate() + ", type=" + getType() + '}';
  }

  public String getType() {
    return type;
  }
}
